### ISSUE TITLE
AccessViolationException in findOverlapping

### ISSUE THREAD

**Issue by fuocor** [geophile/geophile.c#1] opened 2016-03-28 21:52 UTC
Hi,

I have some very large indexes and I validate that the bounds of the box are within the lo and hi of the index, but I am getting arbitrary AccessViolationException when _space->decompose is called in Release builds on Windows.

thanks,
rich

**Comment by geophile** [comment] 2016-03-28 22:26
decompose doesn’t touch the index at all, so the problem is most likely in memory management, (the SessionMemory) or perhaps in the SpatialObject functions used by decompose to probe the object, (e.g. arbitraryPoint, or more likely, containedBy).

What type of spatial object are you using? Something provided with geophile, or one of your own?
Can you send me a test case, or enough code for me to create one?
Does the access violation always occur with the same spatial object? If so, I’d be very interested in a test case with just that spatial object. If not, then that points to other causes.

Of course another possibility is that there is somehow a platform difference. I don’t test at all on Windows.

It would also help if you could fill in some background on your application. Out of curiosity, what are you using for your index layer?

Jack

**Comment by fuocor** [comment] 2016-03-29 18:59
Hi thanks for the quick reply, the code is pretty complex, but the exception is not too hard to reproduce.

I am using the OTB Point2 class with an index bounds of X = 229.89656200, 299.11444200  Y = 20.19199900, 52.80766900   that contains about 4 million points.

if I create a box of 299.09715200, 299.11444200  39.27287300, 39.29568100 which touches the boundary of the index then the exception occurs...

I will run some additional tests where I stretch the index boundaries a little to see what results.

For the moment I am using an unmodified version of your sample index layer which I will harden once my core requirements are met.

thanks,
rich

**Comment by geophile** [comment] 2016-03-29 22:01
I reproduced it using the geophile Box2 class and the boundaries you supplied. I suspect the problem is (literally) an edge case. If the edge of the box is brought in slightly there is no crash. I will work on finding  the root cause. 

Jack

**Comment by geophile** [comment] 2016-03-30 16:33
The problem is in the mapping between the application space and the grid used by geophile.

Geophile is written so that the points of a grid cell include the left and lower boundary of the grid cell, and exclude the top and right. These belong to the neighboring grid cells. So what is happening is that in decomposing the box in quesetion, (299.09715200 : 299.11444200, 39.27287300 : 39.29568100), the right boundary of the box, which lies on the boundary of the space, is considered to belong to the neighboring cell. Space::decompose examines larger and larger regions to find one containing that right boundary and blows up when it tries to create a region larger than the entire space.

The fix is to create a special case for the upper boundary of each dimension, considering it to belong to any region touching that boundary. I should have this fixed in a day or so. (I'm also noticing some build problems that I will fix -- I find cmake quite difficult to work with.)

**Comment by geophile** [comment] 2016-03-31 19:47
Hi Fuocor, let me know how this works.

**Closed as completed by geophile** 2016-03-31 19:47 UTC
